// src/www/v2/widgets/post.vue
<template lang="pug">
  #main(v-html="articleBody")
</template>

<script lang="ts">

import { switcher } from "@common/index";
import { db, initOnce } from "@vStores/index";
import { initCodePlugin } from '@plugins/code';
import { initDesignPlugin } from '@plugins/design';
import { initFigurePlugin } from '@plugins/figure';
import { initHistoryPlugin } from '@plugins/history';
import { initLinkPlugin } from '@plugins/link';
import { initTablePlugin } from '@plugins/table';
import Vue from "vue";
import Component from "vue-class-component";
import { __conf__ } from '@utils/conf';
import { prefetchStyles } from '@md/index';

declare let __portal_to_v2__: string;

@Component
export default class PostComponent extends Vue.extend ( {
  props  : { post: { type: String, default: '=' } },
  methods: {
    restartPlugins (name: string) {
      initCodePlugin ();
      initLinkPlugin ( { postLinkEmitter: ( info: string ) => `${ __portal_to_v2__ }#/post/${ info }` } );
      initTablePlugin ();
      initDesignPlugin ();
      initFigurePlugin ();
      void initHistoryPlugin ( { historyKey: name } );
    },
    async fetchPost () {
      if (!this.$data.db.refresh) return;

      const name = this.$router.currentRoute.params.post;
      const success = await prefetchStyles ( name, db.data.conf, db.data.metas )

      if (!success) return;

      const resp: Response = await fetch ( `${ __conf__.__posts_root__ }${ name }.html?var=${ Date.now () }` )
      this.$data.articleBody = await resp.text();
      
      setTimeout ( this.restartPlugins.bind(this, name), 0);
    }
  },
  computed: {
    onKeyChanged () {
      return switcher (
        () => {
          this.$data.refresh = false;
        },
        () => {
          this.$data.refresh = true;
        },
        200
      );
    }
  },
  watch: {
    post () {
      this.onKeyChanged ();
      this.fetchPost ();
    },
  },
} ) {
  db = db.state;
  refresh = true;
  articleBody = '';

  mounted (): void {
    initOnce ().then ( this.fetchPost );
  }
}

</script>

<style lang="stylus">
#main
  overflow: auto;
  position: relative;
  -webkit-user-select: text;
  user-select: text;
  background: linear-gradient(to bottom, var(--third-theme-color), var(--theme-color) 54vh, var(--theme-color));
  padding: 0.382rem 1rem;
  .markdown-body
    padding: 0.1rem 0.382rem;
    border: solid 1px gray;
    border-radius: 6px;
    box-shadow: 0 0 5px 0 gray;
    @media screen and (max-width: 750px)
      padding: 0 0.382rem;
</style>

// src/www/v1/widgets/post/index.tsx
import './index.scss';

import { initCodePlugin } from '@plugins/code';
import { initDesignPlugin } from '@plugins/design';
import { initFigurePlugin } from '@plugins/figure';
import { initHistoryPlugin } from '@plugins/history';
import { initLinkPlugin } from '@plugins/link';
import { initTablePlugin } from '@plugins/table';
import { I_DB_CTX, injectDBCtx } from '@rCtxs/index';
import { __conf__ } from '@utils/conf';
import React, { Component, ReactElement } from 'react';
import { RouteComponentProps } from 'react-router-dom';
import { prefetchStyles } from '@md/index';

declare let __portal_to_v1__: string;

interface PostProps extends RouteComponentProps<{ name: string }> {
  db: I_DB_CTX;
}

@injectDBCtx ()
export class Post extends Component<PostProps, { articleBody: string }> {

  static restartPlugins ( name: string ): void {
    initCodePlugin ();
    initLinkPlugin ( { postLinkEmitter: ( info: string ) => `${ __portal_to_v1__ }#/post/${ info }` } );
    initTablePlugin ();
    initDesignPlugin ();
    initFigurePlugin ();
    void initHistoryPlugin ( { historyKey: name } );
  }

  constructor ( props: PostProps ) {
    super ( props );

    this.state = { articleBody: '' };
  }

  componentDidMount (): void {
    const { match: { params: { name } }, db: { db: { conf, metas } } } = this.props;

    void prefetchStyles ( name, conf, metas ).then ( this.fetchPost.bind ( this, name ) );
  }

  componentDidUpdate ( prevProps: PostProps ): void {
    const { match: { params: { name } }, db: { db: { conf, metas } } } = this.props;

    if ( name !== prevProps.match.params.name || conf !== prevProps.db.db.conf || metas !== prevProps.db.db.metas ) {
      void prefetchStyles ( name, conf, metas ).then ( this.fetchPost.bind ( this, name ) );
    }
  }

  private async fetchPost ( name: string, success: boolean ) {
    if ( !success ) return;

    this.setState ( {
      articleBody: await ( await fetch (
        `${ __conf__.__posts_root__ }${ name }.html?var=${ Date.now () }`
      ) ).text () },
      Post.restartPlugins.bind ( null, name )
    );
  }

  render (): ReactElement {
    const { articleBody } = this.state;

    return (
      <div className="detail" dangerouslySetInnerHTML={{
        __html: articleBody
      }} />
    );
  }

}
